// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpdyAk-hWN6eoH5GAhgrP236jEQBg0v30',
    appId: '1:416351095316:web:c89ca499e0e5d84f4bf501',
    messagingSenderId: '416351095316',
    projectId: 'odonto-fc4f3',
    authDomain: 'odonto-fc4f3.firebaseapp.com',
    storageBucket: 'odonto-fc4f3.firebasestorage.app',
    measurementId: 'G-NHEHGZM7W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPD-COzjX-UIlf36KyjbayT2lYa6-nGFI',
    appId: '1:416351095316:android:d8a44f5f4d6c22904bf501',
    messagingSenderId: '416351095316',
    projectId: 'odonto-fc4f3',
    storageBucket: 'odonto-fc4f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaBB12sW7-JCTaxm9QfNMh40FAdvT3LMY',
    appId: '1:416351095316:ios:973d41c921d128354bf501',
    messagingSenderId: '416351095316',
    projectId: 'odonto-fc4f3',
    storageBucket: 'odonto-fc4f3.firebasestorage.app',
    iosBundleId: 'com.example.clinicaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaBB12sW7-JCTaxm9QfNMh40FAdvT3LMY',
    appId: '1:416351095316:ios:973d41c921d128354bf501',
    messagingSenderId: '416351095316',
    projectId: 'odonto-fc4f3',
    storageBucket: 'odonto-fc4f3.firebasestorage.app',
    iosBundleId: 'com.example.clinicaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpdyAk-hWN6eoH5GAhgrP236jEQBg0v30',
    appId: '1:416351095316:web:e318e7f6c95d324f4bf501',
    messagingSenderId: '416351095316',
    projectId: 'odonto-fc4f3',
    authDomain: 'odonto-fc4f3.firebaseapp.com',
    storageBucket: 'odonto-fc4f3.firebasestorage.app',
    measurementId: 'G-VJ9P1BK8K5',
  );

}